### ISSUE TITLE
Change script so it does not load map image every time but only if there is a different map needed

### ISSUE THREAD

**Issue by Tonnie78** [Tonnie78/Lua-GPS-Widget#1]
I need to change the script so only a nem map images is loaded when it is needed. I hope this speeds up the operation of the script.

**Comment by lshems** [comment]
Latest pull request fixes this. All maps are preloaded, so even frequent crossing of scale limits should not cause any delay anymore.

**Comment by Tonnie78** [comment]
Does that also mean that every single time when the function bitmap open is run, does not delay hte script?

**Comment by lshems** [comment]
I have to check. The open bitmap is now only done on widget load. So that's good.
The draw bitmap on a colorscreen perhaps doesnt need to be done on every pass. But then you would get a trace of the plane. Need to check.

**Comment by Tonnie78** [comment]
I will try with the code as it is now. Maybe the changes already speed up the process.

**Comment by Tonnie78** [comment]
THe problem was not caused by continues showing of the bitmap. I did change the actual loading of the bitmap to the create function. This greatly increased the speed of the Widget.
