### ISSUE TITLE
change the get.value("GPS") to load based on GPS ID to increase speed

### ISSUE THREAD

**Issue by Tonnie78** [Tonnie78/Lua-GPS-Widget#2]
I read somewhere that it is quicker to first get the numeral ID of the GPS sensor and then use that in the get.value statement to speed up the loading of values from telemetry 

So I need to change that.

**Comment by lshems** [comment]
This is in the case you do very frequent and a lot of reads. Never tested it, but seems not relevant for your script.

**Comment by Tonnie78** [comment]
changed it by using getfieldInfo at the create function
